package org.snturk.petition;

import org.immutables.value.Value;
import jakarta.annotation.Nullable;
import org.snturk.petition.enums.PetitionType;
import org.snturk.petition.model.Issuer;

import java.io.File;
import java.time.LocalDate;
import java.util.Map;
import java.util.function.Function;

@Value.Immutable
@Value.Style(strictBuilder = true)
public interface PetitionModel {

    /**
     * By default id is generated by idGenerator function, but it can be overridden by setting id explicitly.
     * @return
     */
    @Value.Default
    default @Nullable String getId() {
        return getIdGenerator().apply(this);
    }

    /**
     * Name of the petition
     * @return
     */
    String getName();

    /**
     * Title of the petition
     * @return
     */
    String getTitle();

    /**
     * Issuer or signer of the petition
     * @return
     */
    Issuer getIssuer();

    /**
     * Content of the petition
     * @return
     */
    String getContent();

    /**
     * Date of the petition
     * @return
     */
    @Value.Default
    default LocalDate getIssuedDate() {
        return LocalDate.now();
    }

    /**
     * Type of the petition
     * @see PetitionType
     * @return PetitionType
     */
    @Nullable PetitionType getType();

    /**
     * Related attachments of the petition, key is the name of the attachment, value is the java.io.File object
     * @return
     */
    @Nullable Map<String, File> getAttachments();

    /**
     * Function to generate id of the petition
     * @return
     */
    Function<PetitionModel, String> getIdGenerator();
}
