package org.snturk.petition.feedback;

import jakarta.annotation.Nullable;
import org.immutables.value.Value;
import org.snturk.petition.model.Issuer;
import org.snturk.petition.signature.SignatureContext;

import java.io.File;
import java.time.LocalDateTime;
import java.util.Set;
import java.util.function.Function;

/**
 * FeedbackModel definiton to hold petition feedback information.
 */
@Value.Immutable
public interface FeedbackModel {

    static ImmutableFeedbackModel.Builder builder() {
        return ImmutableFeedbackModel.builder();
    }

    /**
     * By default id is generated by idGenerator function, but it can be overridden by setting id explicitly.
     * @return id of the FeedbackModel
     */
    @Value.Default
    default String getId() {
        return getIdGenerator().apply(this);
    }

    /**
     * Id of the PetitionModel, it is filled when the FeedbackModel is linked to a PetitionModel
     * @return id of the PetitionModel
     */
    @Nullable
    String getPetitionId();

    /**
     * Issuer of the FeedbackModel
     * @return Issuer of the FeedbackModel
     */
    Issuer getIssuer();

    /**
     * FeedbackModel message
     * @return FeedbackModel message
     */
    String getContent();

    /**
     * FeedbackModel date
     * @return FeedbackModel date
     */
    @Value.Default
    default LocalDateTime getIssuedDate() {
        return LocalDateTime.now();
    }

    /**
     * Related attachments of the feedback
     * @return Related attachments of the feedback
     */
    Set<File> getAttachments();

    /**
     * Signature context of the feedback
     * @return Signature context of the feedback
     */
    @Nullable
    Set<SignatureContext> getSignatureContext();

    /**
     * Id generator function
     * @return Id generator function
     */
    Function<FeedbackModel, String> getIdGenerator();
}
