package org.snturk.petition.enums;

/**
 * File types that can be generated by the FileGenerationService
 */
public enum FileType {
    /**
     * PDF file type
     */
    PDF, 
    /**
     * DOCX file type
     */
    DOCX, 
    /**
     * HTML file type
     */
    HTML
}
